sampling:
  size: 10
  languages: [en]
  only_media: True
  keywords: [humor,
             meme,
             funny,
             parody,
             joke,
             haha,
             lol]

base-url: https://raw.githubusercontent.com/echen102/COVID-19-TweetIDs/master

twitter:
  consumer_key: <API Key>
  consumer_secret: <API Secret Key>
  access_token: <Access Token>
  access_token_secret: <Access Token Secret>