sampling:
  size: 100
  keywords: [covidhumor,
             coronahumor,
             coronavirushumor,
             coronamemes,
             covidmemes,
             quarantinememes,
             quarantinefunny,
             coronavirusfunny,
             coronavirusparody,
             quarantinehumor,
             quarantinejokes,
             covidjokes]

base-url: https://raw.githubusercontent.com/echen102/COVID-19-TweetIDs/master

twitter:
  consumer_key: 3fJOlJ7bZG5ojjjuqx3j75vvp
  consumer_secret: hMcKeTsBoZYsFZsIHaw6bZ5EbQ5HWXzSiPE3jlKDauSEZRiT4A
  access_token: 984109513945956352-57DTkdhH0QRu5b5hDjES7A6iMSn8HS2
  access_token_secret: rXMBX15IzR2dX0nGLRtToZ97YUIoNbOqfskQTmq93P7Ai
