sampling:
  size: 100
  languages: []
  only_media: True
  keywords: ["#covidhumor",
             "#coronahumor",
             "#coronavirushumor",
             "#coronamemes",
             "#covidmemes",
             "#quarantinememes",
             "#quarantinefunny",
             "#coronavirusfunny",
             "#coronavirusparody",
             "#quarantinehumor",
             "#quarantinejokes",
             "#covidjokes",
             "#coronajokes",
             "#coronavirusjokes",
             "#covidcomedy",
             "#stayinsideandlaugh",
             "#quarantinefun",
             "#covidiots",
             "#COVIDmemes",
             "#coronavirusmemes",
             "#COVID19memes",]

base-url: https://raw.githubusercontent.com/echen102/COVID-19-TweetIDs/master

twitter:
  consumer_key: <API Key>
  consumer_secret: <API Secret Key>
  access_token: <Access Token>
  access_token_secret: <Access Token Secret>
